---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.12.1"
    name: clickhouse

  - src: git@github.com:bolgovsky/vector-role.git
    scm: git
    version: "1.0.1"
    name: vector-role

  - src: git@github.com:bolgovsky/lighthouse-role.git
    scm: git
    version: "1.0.1"
    name: lighthouse-role
